contextwtf/lanyard

- merkle/tree.go
a pervious commit removed the SortPair option. Sorting pairs is enabled and non-optional.
> merkle: fix doc for Valid

- merkle/tree.go
- merkle/tree_test.go
The target need only be hashed once.
Before: BenchmarkProof-10 1 53486735083 ns/op (53.486735083s)
After:  BenchmarkProof-10 4 299320958 ns/op (0.299320958s)
> merkle: fix proof performance

- .github/workflows/deploy-al-prod.yml
adds *.go to prod deploys.
doing this because #32 was not deployed automatically
>  ci: deploy whenever any go file is touched

- .github/workflows/contracts-test.yml
this check ends up being unstable as foundry is pinned to a nightly
version, causing ci failures unrelated to our code
> ci: remove foundry snapshot check

- api/api.go
- api/tracing/main.go
- cmd/api/deploy.sh
- cmd/api/main.go
- go.mod
while we do have tracing set up for some logs, traces aren't currently being sent as the global tracer is not initialized. this adds that
also adds tracing of every db query
> api: set up global tracer if DD_AGENT_HOST is set

- api/migrations/migrations.go
- api/proof.go
- api/schema.sql
- api/tree.go
- api/tree_test.go
- cmd/api/main.go
I don't think it is necessary to store the pre-computed proofs for a
tree in a separate table. In fact, the two tables design yields N
queries for a tree with N leaves. These queries are currently batched,
but I believe we can avoid the work altogether.
I did notice that the current code dealt with duplicate leaves by
selecting the first found proof. On further inspection, it's unclear
what behaviour we should exhibit on duplicate keys. We may want to
return an error on tree creation if we detect duplicate leaves.
> api: store proofs on tree table

- api/tree.go
- cmd/api/main.go
Output from our server on last deploy:
```
{
"level":"info",
"migrated":242,
"time":1660854862,
"caller":"github.com/contextwtf/lanyard/api/tree.go:96",
"message":"success"
}
```
> api: remove tree/proofs migration

- api/api.go
- api/migrations/migrations.go
- api/root.go
- example/src/api.ts
- www/components/Docs/codeSnippets.ts
- www/components/Docs/index.tsx
adds `/api/v1/root`, an endpoint that returns a root
if the proofs are found in the lanyard system.
updated docs and the test script for new endpoint
> api,www: add endpoint for fetching a root from a given proof

- api/migrations/migrations.go
adds an `inserted_at` column to trees. will be useful for
analytics / understanding how people use lanyard
> api: add `inserted_at` to trees table

- api/api.go
adds a log for each request to make lanyard easier to operate - also allows to aid with debugging by adding a way to look up request IDs in log output
> api: add a log for each request

- README.md
- merkle/tree.go
- www/.env
- www/components/Docs/codeSnippets.ts
- www/components/Layout/index.tsx
we own lanyard.org now! awesome. let's merge this in the morning to give dns some time to propagate.
> misc: rename lanyard.build -> lanyard.org

- api/migrations/migrations.go
- api/tree.go
Booleans with 3 possible values are needlessly confusing.
Unpacked data is padded to 32 bytes. Most of the time, callers will
provide a list of [20]byte values (ETH addresses)  --which is packed.
> api: make trees.packed not null

- www/components/Docs/codeSnippets.ts
null was removed as a value in #60, this updates docs
to reflect that
> docs: remove null reference

- api/api.go
most of our request logs are health check requests, let's
omit health from our default request logging
> api: don't log requests to health endpoint

- api/root.go
- api/tree.go
seeing a lot of errors in our logs for 404s. these aren't errors
per se, for logging purposes let's not treat them like one
> api: don't log errors for 404s

- cmd/api/main.go
we're seeing sporadic public read latency. this might be because
the server needs to open up new connections to the pool. let's
try to keep more connections open at a time
> pgx: set a minimum connection count

- api/root.go
this updates the query operator from `@>` to `<@`
by consulting the [pg docs](https://www.postgresql.org/docs/14/functions-array.html), i now believe that this is the best option.
but would appreciate someone double checking my read. running the query, even with a limit 1, seems to a. produce the correct result and b. use the index.
sample query:
```sql
SELECT root                                                                                                                                                              FROM trees                                                                                                                                                                                                     WHERE proofs_array(proofs) <@ proofs_array('[{"proof": …
```
> api: fix root query to be correctly specific

- api/api.go
- api/root.go
- clients/go/lanyard/client.go
- clients/go/lanyard/client_integration_test.go
- example/src/api.ts
- www/components/Docs/codeSnippets.ts
- www/components/Docs/index.tsx
this pull request
- adds the `/v1/roots` endpoint (keeping backwards compat for `/v1/root`)
- adds a message to `/v1/root` about how it's deprecated
- removes `/v1/root` from docs, go client
- adds `/v1/roots` to docs, go client
> api,client,www: add roots endpoint, deprecate root endpoint

- api/proof.go
- api/root.go
- api/tree.go
adds a 60 second cache to:
- 404s on get tree
- 404s on get root
- 404s on get proof
- address lookup on get proof
> api: cache responses

- api/tree.go
there are a lot of merkle trees in the wild with uneven
hex values in it. common javascript libraries pad uneven
byte values with a leading 0. this mimics that behavior
> api: accept uneven length hex strings

- cmd/api/main.go
In production, copyTrees was producing deadlocks. let's attempt to mitigate that by adding a limit, and using `for update skip locked`
> copyTrees: use for update skip locked to avoid deadlocks

- api/migrations/migrations.go
- api/migrations/scripts/000-rebuild-proofs-hashes/main.go
- api/proof.go
- api/root.go
- api/tree.go
- cmd/api/main.go
historically, we've kept a column called `proofs` on the trees table. this is a jsonb column that contained all of the proofs for a tree.
at scale, this caused a couple of issues. the first thing that we saw is that it became too expensive to make a GIN index on proofs at the time of insert. so, we created the `trees_proofs` table which is a copy of the trees table, but replicated in the background with the index. this worked for a while. a couple of weeks ago, we noticed that the `trees` and `trees_proofs` table became out of date. the [background job](https://github.com/contextwtf/lanyard/blob/82f31584ac7f887057170b1b39315ef1380269be/cmd/api/main.go#L37-L54) to backfill the trees was just stalling & deadlocking. we tried a couple of fixes (#97 + #98), but neither worked. this had the …
> fix: simplify data model, proofs_hashes table

- api/migrations/migrations.go
we no longer write or read to `trees_proofs` nor the `proofs` column on trees as of #101. this pull request drops the column.
> cleanup: drop trees_proofs table + proofs columns

- api/tree.go
this information is critical, and after #101 it's very fast (<1ms) to query. let's bring caching in line with that
> trees: lower cache control from one hour to 5 seconds

- api/api.go
- api/proof.go
- go.mod
- go.sum
the proof endpoint has been slow/cpu intensive because it has to fetch+hash every tree. this adds an lru cache to tree that speeds up the endpoint massively for large trees
> proof: add lru cache for trees
